# Generated by Django 5.2.1 on 2025-08-01 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mysales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación del Envío')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('fecha_programada_envio', models.DateField(blank=True, null=True, verbose_name='Fecha Programada de Envío/Recojo')),
                ('fecha_estimada_entrega_cliente', models.DateField(blank=True, null=True, verbose_name='Fecha Estimada de Entrega al Cliente')),
                ('fecha_entrega_real_cliente', models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega Real al Cliente')),
                ('estado_entrega', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('PENDIENTE_RECOJO', 'Pendiente de Recojo (por transportista)'), ('EN_TRANSITO_A_FG', 'En Tránsito (a FG Shop)'), ('RECIBIDO_EN_FG', 'Recibido (en FG Shop)'), ('PREPARANDO_ENVIO_CLIENTE', 'Preparando Envío (a cliente)'), ('EN_RUTA_CLIENTE', 'En Ruta (a cliente)'), ('ENTREGADO', 'Entregado al Cliente'), ('ENTREGA_FALLIDA', 'Entrega Fallida'), ('REPROGRAMADO', 'Reprogramado'), ('DEVUELTO', 'Devuelto')], default='PROGRAMADO', max_length=30, verbose_name='Estado de la Entrega')),
                ('transportista', models.CharField(blank=True, choices=[('OLVA', 'Olva Courier'), ('SHALOM', 'Shalom Empresarial'), ('URBANO', 'Urbano Express'), ('INTERNO_FG', 'Entrega Interna FG Shop'), ('PROVEEDOR_DIRECTO', 'Directo del Proveedor'), ('OTRO', 'Otro')], max_length=50, null=True, verbose_name='Transportista/Empresa de Envío')),
                ('entregado_por_persona', models.CharField(blank=True, max_length=100, null=True, verbose_name='Persona/Repartidor (si aplica)')),
                ('numero_seguimiento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Seguimiento (Tracking)')),
                ('url_seguimiento', models.URLField(blank=True, null=True, verbose_name='URL de Seguimiento')),
                ('costo_real_envio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo Real del Envío (para FG Shop)')),
                ('observaciones_envio', models.TextField(blank=True, null=True, verbose_name='Observaciones del Envío')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_info', to='mysales.order', verbose_name='Pedido Asociado')),
            ],
            options={
                'verbose_name': 'Gestión de Envío',
                'verbose_name_plural': 'Gestión de Envíos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
