# Generated by Django 5.2.1 on 2025-07-19 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mydeliveries', '0001_initial'),
        ('mysales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_info', to='mysales.order', verbose_name='Pedido Asociado'),
        ),
    ]
