# Generated by Django 5.2.1 on 2025-08-01 21:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_direccion', models.CharField(help_text="Ej: 'Casa', 'Oficina de Mamá'", max_length=100)),
                ('destinatario', models.CharField(max_length=200, verbose_name='Nombre del Destinatario')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección (Calle, número, etc.)')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('departamento', models.CharField(max_length=100, verbose_name='Departamento / Región')),
                ('pais', models.CharField(default='Perú', max_length=100)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de Contacto')),
                ('es_principal', models.BooleanField(default=False, verbose_name='¿Es dirección principal?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
                'ordering': ['-es_principal', 'nombre_direccion'],
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DNI', models.CharField(blank=True, max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El DNI debe tener 8 dígitos.', regex='^\\d{8}$')], verbose_name='DNI')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener entre 9 y 15 dígitos, ej: +51987654321 o 987654321.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección Principal')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('title_preference', models.CharField(blank=True, choices=[('PA', 'Patrona'), ('KI', 'mi King')], default=None, max_length=2, null=True, verbose_name='Preferencia de Título')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customerprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Cliente',
                'verbose_name_plural': 'Perfiles de Clientes',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
    ]
