# Generated by Django 5.2.1 on 2025-07-31 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycustomers', '0002_auto_20250625_2211'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_direccion', models.CharField(help_text="Ej: 'Casa', 'Oficina de Mamá'", max_length=100)),
                ('destinatario', models.CharField(max_length=200, verbose_name='Nombre del Destinatario')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección (Calle, número, etc.)')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('departamento', models.CharField(max_length=100, verbose_name='Departamento / Región')),
                ('pais', models.CharField(default='Perú', max_length=100)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de Contacto')),
                ('es_principal', models.BooleanField(default=False, verbose_name='¿Es dirección principal?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
                'ordering': ['-es_principal', 'nombre_direccion'],
            },
        ),
    ]
