# Generated by Django 5.2.1 on 2025-06-26 02:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myproducts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_cliente', models.EmailField(blank=True, help_text='Correo del cliente al momento del pedido.', max_length=254)),
                ('nombre_cliente', models.CharField(blank=True, help_text='Nombre del cliente al momento del pedido.', max_length=200)),
                ('dni_cliente', models.CharField(blank=True, help_text='DNI/Documento del cliente al momento del pedido.', max_length=20)),
                ('direccion_envio', models.TextField(verbose_name='Dirección de Envío')),
                ('ciudad_envio', models.CharField(max_length=100, verbose_name='Ciudad de Envío')),
                ('departamento_envio', models.CharField(max_length=100, verbose_name='Departamento de Envío')),
                ('pais_envio', models.CharField(default='Perú', max_length=100, verbose_name='País de Envío')),
                ('telefono_contacto_envio', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de Contacto (Envío)')),
                ('usar_misma_direccion_facturacion', models.BooleanField(default=True)),
                ('direccion_facturacion', models.TextField(blank=True, null=True, verbose_name='Dirección de Facturación')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Pedido')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('estado_pedido', models.CharField(choices=[('PENDIENTE_PAGO', 'Pendiente de Pago'), ('PAGO_CONFIRMADO', 'Pago Confirmado'), ('PROCESANDO_PROVEEDOR', 'Procesando con Proveedor'), ('EN_CAMINO_A_FGSHOP', 'En camino a FG Shop'), ('LISTO_PARA_ENVIO', 'Listo para Envío (Desde FG Shop)'), ('EN_CAMINO_CLIENTE', 'En Camino al Cliente'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado'), ('REEMBOLSADO', 'Reembolsado')], default='PENDIENTE_PAGO', max_length=30, verbose_name='Estado del Pedido')),
                ('metodo_pago', models.CharField(blank=True, choices=[('TRANSFERENCIA', 'Transferencia Bancaria'), ('EFECTIVO_CONTRAENTREGA', 'Efectivo Contraentrega (Limitado)'), ('PASARELA_ONLINE', 'Pasarela Online (Tarjeta/Yape/Plin)')], max_length=30, null=True, verbose_name='Método de Pago')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Subtotal')),
                ('costo_envio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo de Envío')),
                ('total_pedido', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total del Pedido')),
                ('observaciones_internas', models.TextField(blank=True, help_text='Notas internas para FG Shop sobre este pedido.', null=True)),
                ('observaciones_cliente', models.TextField(blank=True, help_text='Notas del cliente al realizar el pedido.', null=True)),
                ('pagado', models.BooleanField(default=False, verbose_name='¿Pagado?')),
                ('id_transaccion_pago', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Transacción de Pago')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el pedido es visible/activo en el sistema.')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_pedido'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(blank=True, max_length=250, verbose_name='Nombre Completo (Variante)')),
                ('precio_unitario_variante', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio de Venta (Variante)')),
                ('precio_base_producto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Base (Referencial)')),
                ('proveedor_producto', models.CharField(blank=True, max_length=150, verbose_name='Proveedor')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myorders.order', verbose_name='Pedido')),
                ('variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='myproducts.productvariant', verbose_name='Variante de Producto')),
            ],
            options={
                'verbose_name': 'Ítem de Pedido',
                'verbose_name_plural': 'Ítems de Pedidos',
            },
        ),
    ]
