# Generated by Django 5.2.1 on 2025-06-26 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título principal del banner', max_length=200)),
                ('subtitulo', models.CharField(blank=True, help_text='Subtítulo o descripción breve', max_length=300)),
                ('imagen', models.ImageField(help_text='Imagen principal del banner para escritorio (Desktop). Dimensiones recomendadas: Ancho: 1920px - 2560px, Alto: 450px - 600px.', upload_to='banners/')),
                ('imagen_movil', models.ImageField(blank=True, help_text='Imagen optimizada para dispositivos móviles (smartphones y tablets pequeñas). Dimensiones recomendadas: Ancho: 768px - 1024px, Alto: 300px - 450px. Considera que el contenido principal debe estar centrado.', upload_to='banners/mobile/')),
                ('url_destino', models.URLField(blank=True, help_text='URL a la que se redirigirá al hacer clic en el banner')),
                ('texto_boton', models.CharField(blank=True, help_text="Texto que aparecerá en el botón (ej: 'Ver Ofertas')", max_length=50)),
                ('activo', models.BooleanField(default=True, help_text='Marcar para que este banner se muestre en el carrusel')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Define el orden de aparición en el carrusel (menor número = primero)')),
            ],
            options={
                'verbose_name': 'Banner del Carrusel',
                'verbose_name_plural': 'Banners del Carrusel',
                'ordering': ['orden', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='Nombre del Cliente')),
                ('testimonial_text', models.TextField(verbose_name='Testimonio')),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='testimonials/authors/', verbose_name='Imagen del Cliente')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='testimonials/products/', verbose_name='Imagen del Producto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
