# Generated by Django 5.2.1 on 2025-07-19 02:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myproducts', '0003_alter_attributeimage_options_and_more'),
        ('mysuppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(verbose_name='Fecha de Orden')),
                ('expected_delivery_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega Esperada')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('SUBMITTED', 'Enviada al Proveedor'), ('APPROVED', 'Aprobada'), ('PARTIALLY_DELIVERED', 'Entregada Parcialmente'), ('FULLY_DELIVERED', 'Entregada Totalmente'), ('CANCELLED', 'Cancelada')], default='DRAFT', max_length=25, verbose_name='Estado de la Orden')),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº de Factura Proveedor')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Factura')),
                ('payment_due_date', models.DateField(blank=True, null=True, verbose_name='Fecha Vencimiento de Pago')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto Total Ordenado')),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PARTIALLY_PAID', 'Pagada Parcialmente'), ('FULLY_PAID', 'Pagada Totalmente'), ('OVERPAID', 'Sobrepagada')], default='PENDING', max_length=20, verbose_name='Estado del Pago')),
                ('document_file', models.FileField(blank=True, null=True, upload_to='purchase_invoices/%Y/%m/', verbose_name='Archivo de Factura/Guía')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas / Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='mysuppliers.supplier', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(verbose_name='Fecha de Entrega')),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Seguimiento')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas de Entrega')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Recibido por')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='mypurchases.purchaseorder', verbose_name='Orden de Compra')),
            ],
            options={
                'verbose_name': 'Recepción de Mercadería',
                'verbose_name_plural': 'Recepciones de Mercadería',
                'ordering': ['-delivery_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad Pedida')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo por Unidad (sin IGV)')),
                ('received_quantity', models.PositiveIntegerField(default=0, verbose_name='Cantidad Recibida')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mypurchases.purchaseorder', verbose_name='Orden de Compra')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='myproducts.productvariant', verbose_name='Variante de Producto')),
            ],
            options={
                'verbose_name': 'Ítem de Orden de Compra',
                'verbose_name_plural': 'Ítems de Órdenes de Compra',
                'unique_together': {('purchase_order', 'variant')},
            },
        ),
        migrations.CreateModel(
            name='PurchaseDeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.PositiveIntegerField(verbose_name='Cantidad Recibida en esta entrega')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mypurchases.purchasedelivery', verbose_name='Recepción')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_items', to='mypurchases.purchaseorderitem', verbose_name='Ítem de la Orden')),
            ],
            options={
                'verbose_name': 'Ítem Recibido',
                'verbose_name_plural': 'Ítems Recibidos',
            },
        ),
        migrations.CreateModel(
            name='PurchasePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(verbose_name='Fecha de Pago')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Monto Pagado')),
                ('payment_method', models.CharField(help_text='Ej: Transferencia BCP, Yape, Efectivo', max_length=100, verbose_name='Método de Pago')),
                ('reference_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Referencia/Operación')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='mypurchases.purchaseorder', verbose_name='Orden de Compra')),
            ],
            options={
                'verbose_name': 'Pago de Compra',
                'verbose_name_plural': 'Pagos de Compras',
                'ordering': ['-payment_date'],
            },
        ),
    ]
