# Generated by Django 5.2.1 on 2025-07-19 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypurchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente de Recepción'), ('RECEIVED', 'Recibido Completamente')], default='PENDING', max_length=20, verbose_name='Estado del Ítem'),
        ),
    ]
