# Generated by Django 5.2.1 on 2025-07-24 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypurchases', '0002_purchaseorderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='installment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto por cuota'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='installments_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Número de cuotas'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='is_installment',
            field=models.BooleanField(default=False, verbose_name='¿Es compra a cuotas?'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo de Envío'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Subtotal (Productos)'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto Total (incl. envío)'),
        ),
    ]
