# Generated by Django 5.2.1 on 2025-07-25 13:23

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypurchases', '0003_purchaseorder_installment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasepayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto Pagado'),
        ),
    ]
