# Generated by Django 5.2.1 on 2025-07-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypurchases', '0004_alter_purchasepayment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasepayment',
            name='receipt_file',
            field=models.FileField(blank=True, null=True, upload_to='purchase_payments/%Y/%m/', verbose_name='Comprobante de Pago'),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='payment_method',
            field=models.CharField(choices=[('TRANSFERENCIA_BCP', 'Transferencia BCP'), ('TRANSFERENCIA_INTERBANK', 'Transferencia Interbank'), ('YAPE', 'Yape'), ('PLIN', 'Plin'), ('EFECTIVO', 'Efectivo'), ('TARJETA_CREDITO', 'Tarjeta de Crédito'), ('OTRO', 'Otro')], max_length=50, verbose_name='Método de Pago'),
        ),
    ]
