# Generated by Django 5.2.1 on 2025-09-12 13:36

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myproducts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=255, verbose_name='Razón Social')),
                ('ruc', models.CharField(max_length=11, verbose_name='RUC')),
                ('atencion_a', models.CharField(blank=True, max_length=255, verbose_name='Atención a')),
                ('email_cliente', models.EmailField(blank=True, max_length=254, verbose_name='Email de Contacto')),
                ('telefono_cliente', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de Contacto')),
                ('numero_cotizacion', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Nº Cotización')),
                ('fecha_emision', models.DateField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('fecha_validez', models.DateField(verbose_name='Válida hasta')),
                ('estado', models.CharField(choices=[('DRAFT', 'Borrador'), ('SENT', 'Enviada'), ('ACCEPTED', 'Aceptada'), ('REJECTED', 'Rechazada'), ('EXPIRED', 'Expirada')], default='DRAFT', max_length=10, verbose_name='Estado')),
                ('terminos_y_condiciones', models.TextField(blank=True, default='Garantía: 12 meses por defectos de fábrica. No incluye daños por mal uso.\nTiempo de entrega: 3-5 días hábiles una vez confirmado el pago.\nValidez de la oferta: Sujeta a la fecha indicada en el documento.', verbose_name='Términos y Condiciones')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones Adicionales')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('igv', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, help_text='Se autocompleta desde el producto, pero se puede editar.', max_length=255)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Unitario (Sin IGV)')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myquotes.quote', verbose_name='Cotización')),
                ('variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_items', to='myproducts.productvariant', verbose_name='Producto (Variante)')),
            ],
            options={
                'verbose_name': 'Ítem de Cotización',
                'verbose_name_plural': 'Ítems de Cotización',
            },
        ),
    ]
