# Generated by Django 5.2.1 on 2025-09-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myquotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='direccion_cliente',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='terminos_y_condiciones',
            field=models.TextField(blank=True, default='Garantía: 12 meses por defectos de fábrica. No incluye daños por mal uso.\nTiempo de entrega: 7-10 días hábiles una vez confirmada la compra.\nValidez de la oferta: Sujeta a la fecha indicada en el documento.', verbose_name='Términos y Condiciones'),
        ),
    ]
