# Generated by Django 5.2.1 on 2025-08-01 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mysuppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del atributo (ej. Color, Talla)', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Slug para uso interno o URLs', max_length=110, unique=True)),
            ],
            options={
                'verbose_name': 'Atributo',
                'verbose_name_plural': 'Atributos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Marca')),
                ('slug', models.SlugField(blank=True, help_text='Versión amigable para URL, se genera automáticamente.', max_length=110, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='Logo de la Marca')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción de la Marca')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EspecificacionPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Ej: 'Plantilla para Ropa', 'Plantilla para Celulares'", max_length=100, unique=True)),
                ('claves', models.TextField(help_text="Lista de claves de especificación, una por línea. Ej: 'Material', 'País de origen', etc.")),
            ],
            options={
                'verbose_name': 'Plantilla de Especificaciones',
                'verbose_name_plural': 'Plantillas de Especificaciones',
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Valor del atributo (ej. Rojo, S, Algodón)', max_length=100)),
                ('color_code', models.CharField(blank=True, help_text='Código de color hexadecimal (ej. #FF0000) si este atributo es un color.', max_length=7, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='myproducts.attribute', verbose_name='Atributo')),
            ],
            options={
                'verbose_name': 'Valor de Atributo',
                'verbose_name_plural': 'Valores de Atributos',
                'ordering': ['attribute', 'value'],
                'unique_together': {('attribute', 'value')},
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=110)),
                ('imagen_categoria', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Imagen de la Categoría')),
                ('guia_tallas_pdf', models.FileField(blank=True, null=True, upload_to='guides/sizes/', verbose_name='Guía de Tallas (PDF)')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='myproducts.categoria', verbose_name='Categoría Padre')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
                'unique_together': {('padre', 'nombre'), ('padre', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('especificaciones', models.JSONField(blank=True, default=dict, help_text='Almacena las especificaciones del producto como un diccionario JSON. Ejemplo: {"Marca": "Nike", "Material": "Cuero"}', null=True, verbose_name='Especificaciones Técnicas')),
                ('precio_base', models.DecimalField(blank=True, decimal_places=2, help_text='Precio base si el producto no tiene variantes o como referencia.', max_digits=10, null=True)),
                ('use_variant_specific_images', models.BooleanField(default=False, help_text='Marcar si las imágenes dependen de la variante completa (ej. por peso) en lugar del atributo visual (ej. color).', verbose_name='Usar Imágenes por Variante Específica')),
                ('acepta_cuotas', models.BooleanField(default=False, help_text='Marcar si este producto puede ser pagado en cuotas.', verbose_name='Acepta pago en cuotas')),
                ('numero_de_cuotas', models.PositiveIntegerField(default=12, help_text='Número máximo de cuotas para este producto (ej. 3, 6, 12).', verbose_name='Número de cuotas')),
                ('activo', models.BooleanField(default=True)),
                ('destacado', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_marca', to='myproducts.brand', verbose_name='Marca')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='myproducts.categoria')),
                ('configurable_attributes', models.ManyToManyField(blank=True, help_text='Atributos que se usarán para crear variantes de este producto (ej. Talla, Color).', related_name='configurable_products', to='myproducts.attribute')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_supplied', to='mysuppliers.supplier', verbose_name='Proveedor')),
                ('visual_attribute', models.ForeignKey(blank=True, help_text='El atributo que controla las imágenes (ej. Color para ropa, Sabor para suplementos).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visual_for_products', to='myproducts.attribute', verbose_name='Atributo Visual Principal')),
            ],
            options={
                'verbose_name': 'Producto (Maestro)',
                'verbose_name_plural': 'Productos (Maestros)',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, editable=False, max_length=100, unique=True)),
                ('nombre_variante', models.CharField(blank=True, help_text='Nombre descriptivo (ej. Rojo / M). Se autogenera.', max_length=255)),
                ('precio_variante', models.DecimalField(decimal_places=2, help_text='Precio específico de esta variante.', max_digits=10)),
                ('stock_disponible', models.PositiveIntegerField(default=0, help_text='Stock para esta variante específica.')),
                ('activo', models.BooleanField(default=True, help_text='¿Está esta variante disponible?')),
                ('costo_proveedor_estimado_variante', models.DecimalField(blank=True, decimal_places=2, help_text='Costo para esta variante.', max_digits=10, null=True)),
                ('tiempo_entrega_estimado_variante', models.CharField(blank=True, help_text='Tiempo de entrega para esta variante.', max_length=100, null=True)),
                ('options', models.ManyToManyField(related_name='product_variants', to='myproducts.attributevalue', verbose_name='Opciones de Atributo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='myproducts.product', verbose_name='Producto Maestro')),
            ],
            options={
                'verbose_name': 'Variante de Producto',
                'verbose_name_plural': 'Variantes de Productos',
                'unique_together': {('product', 'nombre_variante')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='default_variant',
            field=models.OneToOneField(blank=True, help_text='Variante que se muestra/usa por defecto si existe.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_product', to='myproducts.productvariant'),
        ),
        migrations.CreateModel(
            name='AttributeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='attribute_images/%Y/%m/%d/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('orden_visualizacion', models.PositiveIntegerField(default=0)),
                ('attribute_value', models.ForeignKey(blank=True, help_text="Asocia imágenes a un valor de atributo (ej. 'Color: Negro'). Usar para el modo de imagen estándar.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myproducts.attributevalue')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute_images', to='myproducts.product')),
                ('variant', models.ForeignKey(blank=True, help_text="Asocia esta imagen a una variante específica. Usar solo si se marcó 'Usar Imágenes por Variante'.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specific_images', to='myproducts.productvariant')),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Imágenes de Productos',
                'ordering': ['orden_visualizacion'],
            },
        ),
    ]
