# Generated by Django 5.2.1 on 2025-07-09 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproducts', '0002_product_visual_attribute'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributeimage',
            options={'ordering': ['orden_visualizacion'], 'verbose_name': 'Imagen de Producto', 'verbose_name_plural': 'Imágenes de Productos'},
        ),
        migrations.AlterUniqueTogether(
            name='attributeimage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attributeimage',
            name='variant',
            field=models.ForeignKey(blank=True, help_text="Asocia esta imagen a una variante específica. Usar solo si se marcó 'Usar Imágenes por Variante'.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specific_images', to='myproducts.productvariant'),
        ),
        migrations.AddField(
            model_name='product',
            name='use_variant_specific_images',
            field=models.BooleanField(default=False, help_text='Marcar si las imágenes dependen de la variante completa (ej. por peso) en lugar del atributo visual (ej. color).', verbose_name='Usar Imágenes por Variante Específica'),
        ),
        migrations.AlterField(
            model_name='attributeimage',
            name='attribute_value',
            field=models.ForeignKey(blank=True, help_text="Asocia imágenes a un valor de atributo (ej. 'Color: Negro'). Usar para el modo de imagen estándar.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myproducts.attributevalue'),
        ),
    ]
