# Generated by Django 5.2.1 on 2025-06-26 02:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=150, verbose_name='Nombre de la Empresa/Proveedor')),
                ('ruc', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='El RUC debe tener 11 dígitos.', regex='^\\d{11}$')], verbose_name='RUC')),
                ('nombre_contacto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Contacto Principal')),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='El número de teléfono es inválido.', regex='^\\+?1?\\d{7,15}$')], verbose_name='Teléfono de Contacto')),
                ('correo_contacto', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico de Contacto')),
                ('sitio_web', models.URLField(blank=True, null=True, verbose_name='Sitio Web')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='suppliers/logos/', verbose_name='Logo de la Empresa')),
                ('direccion_fiscal', models.TextField(blank=True, null=True, verbose_name='Dirección Fiscal')),
                ('direccion_almacen', models.TextField(blank=True, null=True, verbose_name='Dirección de Almacén/Recojo (si aplica)')),
                ('tipo_proveedor', models.CharField(blank=True, choices=[('MAYORISTA', 'Mayorista'), ('FABRICANTE', 'Fabricante'), ('DISTRIBUIDOR', 'Distribuidor'), ('MINORISTA_ESPECIAL', 'Minorista Especializado'), ('OTRO', 'Otro')], max_length=25, null=True, verbose_name='Tipo de Proveedor')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('EN_EVALUACION', 'En Evaluación')], default='ACTIVO', max_length=15, verbose_name='Estado del Proveedor')),
                ('terminos_pago', models.CharField(blank=True, help_text='Ej: Contado, Crédito 30 días', max_length=100, null=True, verbose_name='Términos de Pago Acordados')),
                ('tiempo_entrega_promedio_a_fg', models.CharField(blank=True, help_text='Ej: 2-3 días, 1 semana', max_length=50, null=True, verbose_name='Tiempo Promedio de Entrega (a FG Shop)')),
                ('calificacion_interna', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Calificación Interna (1-5)')),
                ('observaciones_generales', models.TextField(blank=True, null=True, verbose_name='Observaciones Generales')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre_empresa'],
            },
        ),
    ]
