# Generated by Django 5.2.1 on 2025-08-01 21:09

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myproducts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Nombre del Cliente')),
                ('customer_dni', models.CharField(blank=True, max_length=20, verbose_name='DNI del Cliente')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono del Cliente')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email del Cliente')),
                ('sale_date', models.DateField(verbose_name='Fecha del Acuerdo')),
                ('product_cash_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Original al Contado')),
                ('initial_payment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Cuota Inicial')),
                ('interest_rate', models.FloatField(default=0.0, verbose_name='Tasa de Interés (%)')),
                ('number_of_installments', models.PositiveIntegerField(verbose_name='Número de Cuotas')),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto de cada Cuota')),
                ('total_credit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Total a Crédito (Calculado)')),
                ('status', models.CharField(choices=[('ACTIVE', 'Vigente'), ('PAID_OFF', 'Pagado Completamente'), ('LATE', 'En Atraso'), ('CANCELLED', 'Cancelado')], default='ACTIVE', max_length=20, verbose_name='Estado del Crédito')),
                ('notes', models.TextField(blank=True, verbose_name='Notas del Acuerdo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installment_sales', to=settings.AUTH_USER_MODEL, verbose_name='Cliente (Opcional)')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myproducts.productvariant', verbose_name='Variante Vendida')),
            ],
            options={
                'verbose_name': 'Venta a Cuotas',
                'verbose_name_plural': 'Ventas a Cuotas',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='InstallmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(verbose_name='Fecha de Pago')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Pagado')),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='installment_receipts/%Y/%m/', verbose_name='Comprobante de Cuota')),
                ('notes', models.TextField(blank=True, verbose_name='Notas del Pago')),
                ('installment_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='mysales.installmentsale', verbose_name='Venta a Crédito')),
            ],
            options={
                'verbose_name': 'Pago de Cuota',
                'verbose_name_plural': 'Pagos de Cuotas',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_cliente', models.EmailField(blank=True, help_text='Correo del cliente al momento del pedido.', max_length=254)),
                ('nombre_cliente', models.CharField(blank=True, help_text='Nombre del cliente al momento del pedido.', max_length=200)),
                ('dni_cliente', models.CharField(blank=True, help_text='DNI/Documento del cliente al momento del pedido.', max_length=20)),
                ('direccion_envio', models.TextField(verbose_name='Dirección de Envío')),
                ('ciudad_envio', models.CharField(max_length=100, verbose_name='Ciudad de Envío')),
                ('departamento_envio', models.CharField(max_length=100, verbose_name='Departamento de Envío')),
                ('pais_envio', models.CharField(default='Perú', max_length=100, verbose_name='País de Envío')),
                ('telefono_contacto_envio', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de Contacto (Envío)')),
                ('usar_misma_direccion_facturacion', models.BooleanField(default=True)),
                ('direccion_facturacion', models.TextField(blank=True, null=True, verbose_name='Dirección de Facturación')),
                ('tipo_comprobante', models.CharField(choices=[('BOLETA', 'Boleta de Venta'), ('FACTURA', 'Factura')], default='BOLETA', max_length=10, verbose_name='Tipo de Comprobante')),
                ('ruc', models.CharField(blank=True, max_length=11, null=True, verbose_name='RUC')),
                ('razon_social', models.CharField(blank=True, max_length=200, null=True, verbose_name='Razón Social')),
                ('direccion_fiscal', models.TextField(blank=True, null=True, verbose_name='Dirección Fiscal (Factura)')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Pedido')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('estado_pedido', models.CharField(choices=[('PENDIENTE_PAGO', 'Pendiente de Pago'), ('PAGO_CONFIRMADO', 'Pago Confirmado'), ('PROCESANDO_PROVEEDOR', 'Procesando con Proveedor'), ('EN_CAMINO_A_FGSHOP', 'En camino a FG Shop'), ('LISTO_PARA_ENVIO', 'Listo para Envío (Desde FG Shop)'), ('EN_CAMINO_CLIENTE', 'En Camino al Cliente'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado'), ('REEMBOLSADO', 'Reembolsado')], default='PENDIENTE_PAGO', max_length=30, verbose_name='Estado del Pedido')),
                ('metodo_pago', models.CharField(blank=True, choices=[('TRANSFERENCIA_BCP', 'Transferencia BCP'), ('TRANSFERENCIA_INTERBANK', 'Transferencia Interbank'), ('YAPE', 'Yape'), ('PLIN', 'Plin'), ('EFECTIVO', 'Efectivo'), ('TARJETA_CREDITO', 'Tarjeta de Crédito'), ('OTRO', 'Otro')], max_length=30, null=True, verbose_name='Método de Pago')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Subtotal')),
                ('costo_envio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Costo de Envío')),
                ('total_pedido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total del Pedido')),
                ('observaciones_internas', models.TextField(blank=True, help_text='Notas internas para FG Shop sobre este pedido.', null=True)),
                ('observaciones_cliente', models.TextField(blank=True, help_text='Notas del cliente al realizar el pedido.', null=True)),
                ('pagado', models.BooleanField(default=False, verbose_name='¿Pagado?')),
                ('id_transaccion_pago', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Transacción de Pago')),
                ('payment_receipt_file', models.FileField(blank=True, null=True, upload_to='sales_receipts/%Y/%m/', verbose_name='Archivo del Comprobante de Pago')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el pedido es visible/activo en el sistema.')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Orden de Venta (Contado)',
                'verbose_name_plural': 'Órdenes de Venta (Contado)',
                'ordering': ['-fecha_pedido'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(blank=True, max_length=250, verbose_name='Nombre Completo (Variante)')),
                ('precio_unitario_variante', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio de Venta (Variante)')),
                ('precio_base_producto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Base (Referencial)')),
                ('proveedor_producto', models.CharField(blank=True, max_length=150, verbose_name='Proveedor')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mysales.order', verbose_name='Pedido')),
                ('variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='myproducts.productvariant', verbose_name='Variante de Producto')),
            ],
            options={
                'verbose_name': 'Ítem de Venta',
                'verbose_name_plural': 'Ítems de Venta',
            },
        ),
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(verbose_name='Fecha de Pago')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Pagado')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Método de Pago')),
                ('reference_code', models.CharField(blank=True, max_length=100, verbose_name='Código de Referencia/Transacción')),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='sale_installments_receipts/%Y/%m/', verbose_name='Comprobante de Cuota')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='mysales.order', verbose_name='Orden de Venta')),
            ],
            options={
                'verbose_name': 'Pago de Venta',
                'verbose_name_plural': 'Pagos de Ventas',
                'ordering': ['-payment_date'],
            },
        ),
    ]
