# Generated by Django 5.2.1 on 2025-09-03 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentsale',
            name='fecha_primer_pago',
            field=models.DateField(blank=True, help_text='Si se deja en blanco, la primera cuota será un mes después de la Fecha del Acuerdo.', null=True, verbose_name='Fecha de la Primera Cuota'),
        ),
    ]
