# Generated by Django 5.2.1 on 2025-07-21 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='installment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto por cuota'),
        ),
        migrations.AddField(
            model_name='order',
            name='installments_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Número de cuotas'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_installment',
            field=models.BooleanField(default=False, verbose_name='¿Es venta a cuotas?'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_receipt_file',
            field=models.FileField(blank=True, null=True, upload_to='sales_receipts/%Y/%m/', verbose_name='Archivo del Comprobante de Pago'),
        ),
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(verbose_name='Fecha de Pago')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Pagado')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Método de Pago')),
                ('reference_code', models.CharField(blank=True, max_length=100, verbose_name='Código de Referencia/Transacción')),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='sale_installments_receipts/%Y/%m/', verbose_name='Comprobante de Cuota')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='mysales.order', verbose_name='Orden de Venta')),
            ],
            options={
                'verbose_name': 'Pago de Venta',
                'verbose_name_plural': 'Pagos de Ventas',
                'ordering': ['-payment_date'],
            },
        ),
    ]
