# Generated by Django 5.2.1 on 2025-07-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysales', '0002_order_installment_amount_order_installments_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('TRANSFERENCIA_BCP', 'Transferencia BCP'), ('TRANSFERENCIA_INTERBANK', 'Transferencia Interbank'), ('YAPE', 'Yape'), ('PLIN', 'Plin'), ('EFECTIVO', 'Efectivo'), ('TARJETA_CREDITO', 'Tarjeta de Crédito'), ('OTRO', 'Otro')], max_length=30, null=True, verbose_name='Método de Pago'),
        ),
    ]
