# Generated by Django 5.2.1 on 2025-07-25 14:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproducts', '0003_alter_attributeimage_options_and_more'),
        ('mysales', '0003_alter_order_metodo_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-fecha_pedido'], 'verbose_name': 'Orden de Venta (Contado)', 'verbose_name_plural': 'Órdenes de Venta (Contado)'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='installment_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='installments_count',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_installment',
        ),
        migrations.CreateModel(
            name='InstallmentSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(verbose_name='Fecha del Acuerdo')),
                ('product_cash_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Original al Contado')),
                ('initial_payment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Cuota Inicial')),
                ('interest_rate', models.FloatField(default=0.0, verbose_name='Tasa de Interés (%)')),
                ('number_of_installments', models.PositiveIntegerField(verbose_name='Número de Cuotas')),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto de cada Cuota')),
                ('total_credit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Total a Crédito (Calculado)')),
                ('status', models.CharField(choices=[('ACTIVE', 'Vigente'), ('PAID_OFF', 'Pagado Completamente'), ('LATE', 'En Atraso'), ('CANCELLED', 'Cancelado')], default='ACTIVE', max_length=20, verbose_name='Estado del Crédito')),
                ('notes', models.TextField(blank=True, verbose_name='Notas del Acuerdo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installment_sales', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myproducts.productvariant', verbose_name='Variante Vendida')),
            ],
            options={
                'verbose_name': 'Venta a Cuotas',
                'verbose_name_plural': 'Ventas a Cuotas',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='InstallmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(verbose_name='Fecha de Pago')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Pagado')),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='installment_receipts/%Y/%m/', verbose_name='Comprobante de Cuota')),
                ('notes', models.TextField(blank=True, verbose_name='Notas del Pago')),
                ('installment_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='mysales.installmentsale', verbose_name='Venta a Crédito')),
            ],
            options={
                'verbose_name': 'Pago de Cuota',
                'verbose_name_plural': 'Pagos de Cuotas',
                'ordering': ['-payment_date'],
            },
        ),
    ]
