# Generated by Django 5.2.1 on 2025-07-25 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysales', '0004_alter_order_options_remove_order_installment_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentsale',
            name='customer_dni',
            field=models.CharField(blank=True, max_length=20, verbose_name='DNI del Cliente'),
        ),
        migrations.AddField(
            model_name='installmentsale',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email del Cliente'),
        ),
        migrations.AddField(
            model_name='installmentsale',
            name='customer_name',
            field=models.CharField(default='', max_length=200, verbose_name='Nombre del Cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installmentsale',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono del Cliente'),
        ),
        migrations.AlterField(
            model_name='installmentsale',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installment_sales', to=settings.AUTH_USER_MODEL, verbose_name='Cliente (Opcional)'),
        ),
    ]
