# Generated by Django 5.2.1 on 2025-07-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysales', '0005_installmentsale_customer_dni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='direccion_fiscal',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección Fiscal (Factura)'),
        ),
        migrations.AddField(
            model_name='order',
            name='razon_social',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Razón Social'),
        ),
        migrations.AddField(
            model_name='order',
            name='ruc',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='RUC'),
        ),
        migrations.AddField(
            model_name='order',
            name='tipo_comprobante',
            field=models.CharField(choices=[('BOLETA', 'Boleta de Venta'), ('FACTURA', 'Factura')], default='BOLETA', max_length=10, verbose_name='Tipo de Comprobante'),
        ),
    ]
